#!/usr/bin/with-contenv bash
set -e

export ICECAST_ADMIN_EMAIL=${ICECAST_ADMIN_EMAIL:-icemaster@localhost}
export ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD:-$(uuidgen)}
export ICECAST_ADMIN_USER=${ICECAST_ADMIN_USER:-admin}
export ICECAST_HOSTNAME=${ICECAST_HOSTNAME:-localhost}
export ICECAST_LOCATION=${ICECAST_LOCATION:-Earth}
export ICECAST_RELAY_PASSWORD=${ICECAST_RELAY_PASSWORD:-$(uuidgen)}
export ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD:-$(uuidgen)}

confd -onetime -backend env

chown root.icecast /etc/icecast2/icecast.xml
chmod 0640 /etc/icecast2/icecast.xml

cat /etc/icecast2/icecast.xml
